export const ADD_ELEMENT = 'ADD_ELEMENT'
export const ADD_ELEMENT_TRUE = 'ADD_ELEMENT_TRUE'
export const ADD_ELEMENT_FALSE = 'ADD_ELEMENT_FALSE'

export const LIST_ELEMENTS = 'LIST_ELEMENTS'
export const LIST_ELEMENTS_TRUE = 'LIST_ELEMENTS_TRUE'
export const LIST_ELEMENTS_FALSE = 'LIST_ELEMENTS_FALSE'
