export const ADD_ELEMENT = 'ADD_ELEMENT'
export const ADD_ELEMENT_TRUE = 'ADD_ELEMENT_TRUE'
export const ADD_ELEMENT_FALSE = 'ADD_ELEMENT_FALSE'

export const LIST_ELEMENTS = 'LIST_ELEMENTS'
export const LIST_ELEMENTS_TRUE = 'LIST_ELEMENTS_TRUE'
export const LIST_ELEMENTS_FALSE = 'LIST_ELEMENTS_FALSE'

export const DELETE_ELEMENT = 'DELETE_ELEMENT'
export const DELETE_ELEMENT_TRUE = 'DELETE_ELEMENT_TRUE'
export const DELETE_ELEMENT_FALSE = 'DELETE_ELEMENT_FALSE'

export const EDIT_ELEMENT = 'EDIT_ELEMENT'
export const START_EDIT_ELEMENT = 'START_EDIT_ELEMENT'
export const EDIT_ELEMENT_TRUE = 'EDIT_ELEMENT_TRUE'
export const EDIT_ELEMENT_FALSE = 'EDIT_ELEMENT_FALSE'

export const ALERT_ELEMENT_ON = 'ALERT_ELEMENT_ON'
export const ALERT_ELEMENT_OFF = 'ALERT_ELEMENT_OFF'